import { createClient } from "@/modules/core/lib/supabase/server";
import { Metadata } from "next";
import { redirect } from "next/navigation";
import { AppSidebar } from "@/modules/dashboard/components/app-sidebar";
import { Separator } from "@/modules/core/components/ui/separator";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/modules/core/components/ui/sidebar";
import BreadcrumbMain from "@/modules/dashboard/components/breadcrumb-main";

export const metadata: Metadata = {
  title: "Sistema",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();

  const { data, error } = await supabase.auth.getUser();
  if (error || !data?.user) {
    redirect("/login");
  }
  return (
    <SidebarProvider>
      <AppSidebar />
      <SidebarInset>
        <header className="flex h-16 shrink-0 items-center gap-2">
          <div className="flex items-center gap-2 px-4">
            <SidebarTrigger className="-ml-1" />
            <Separator orientation="vertical" className="mr-2 h-4" />
            <BreadcrumbMain />
          </div>
        </header>
        <div className="p-4 pt-0">{children}</div>
      </SidebarInset>
    </SidebarProvider>
  );
}
